app:
  browser:
    name: chrome
    resolution:
      width: 1920
      height: 1080
    maximized: true
    headless: false
spring:
  profiles:
    active: prod
logging:
  level:
    root: info
    com.iamalexvybornyi.playwright.test.project: debug